services:
  movie-postgres:
    image: postgres:15
    container_name: movie_container
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"